version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: my-postgres-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: database
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - postgres-network

volumes:
  postgres_data:
    name: postgres_data

networks:
  postgres-network:
    name: postgres-network
    driver: bridge